### ISSUE TITLE
Whitespace token alignment with spec

### ISSUE THREAD

**Issue by JLHwung** [jonathantneal/postcss-system-ui-font#1]
The spec [defines](https://www.w3.org/TR/css-syntax-3/#whitespace) whitespace token as

> A newline, U+0009 CHARACTER TABULATION, or U+0020 SPACE.

However, [here](https://github.com/jonathantneal/postcss-system-ui-font/blob/master/index.js#L25) we try to match the whitespace using EcmaScript `\s` pattern, which might cause interoperability issues, though the usecase is extremely rare and mostly theoretical.

Example
```js
/\s/.test("\u00A0")
// returns true
```
But `\u00A0` is not defined as a whitespace token so we should not strip `\u00A0`.

We can replace `\s` by `[\n\r\x09\x20]` for strict compliance.

**Comment by jonathantneal** [comment]
Thanks for noticing this!

How did anyone even find this? This is a [generated repository](https://github.com/jonathantneal/postcss-boilerplate/) that I made last night. It is not published, and I only needed it to get postcss-preset-env working, because `postcss-font-family-system-ui` has a dependency on `@std/esm` that is giving me issues.

As you are the original author of postcss-font-family-system-ui, may we turn this repo into a PR to yours? I would not like to publish this repo. I _can_ publish it under the `@csstools` namespace if `@std/esm` is a hard requirement, but I’m not prepared to do so. I would also like you to make you an admin of this repo, and we need to add you to the package.json.

I’m actually very sorry that you found this repo before I had a chance to reach out to you. Out of pure curiosity, how _did_ you find this?

**Comment by JLHwung** [comment]
Hi Jonathan,

A recent updates of `@std/esm` [breaks](https://github.com/standard-things/esm/issues/239) `postcss-font-family-system-ui` and fixed today. The 2.1.4 release of `postcss-font-family-system-ui` should be good to use.

`@std/esm` has add `postcss-font-family-system-ui` to its scenario test so I assumes no further semver-patch breakage.

> turn this repo into a PR to yours?

It is okay to un-depends `postcss-value-parser` since the plugin is pretty simple and straightforward, but we should use regex really really carefully since we skip the parser phrase.

I use `postcss-value-parser` because most other more powerful postcss plugins just depends it. As the end-user will not typically use `postcss-font-family-system-ui` alone, one will use `postcss-cssnext` or other presets that is very likely implicitly depends on `postcss-value-parser`. So the dependence should not add burden to the end-user.

I do consider to generate a rollup builds for package `index` so that `@std/esm` is not a hard requirement for end-user. I use `esm` because node.js 10 is coming at April with ESM module support. I want to give it a try and remove `esm` one day as I remove `babel` without impacting the code. 😄

> how did you find this?

As recent `@std/esm` breaks `postcss-font-family-system-ui`, I check its dependents to evaluate the possible impact. Then I find `postcss-preset-env` 2.0 and this plugin. It is a great and handy project.

I regret I published `postcss-preset-env` 1.0 by accident. 😫

**Comment by RyanZim** [comment]
Just chiming in here; I'm also maintaining a rollup bundle version of `postcss-font-family-system-ui` for browserify use: https://github.com/RyanZim/postcss-font-family-system-ui-commonjs. If we could get rollup added to `postcss-font-family-system-ui`, I'd be glad to kill that fork.

**Comment by jonathantneal** [comment]
Resolved the original issue via https://github.com/jonathantneal/postcss-system-ui-font/commit/e8248124fcb7adda9bb7357d377433a7702f9b2d#diff-168726dbe96b3ce427e7fedce31bb0bcR25

PR submitted here to @JLHwung’s repo https://github.com/JLHwung/postcss-font-family-system-ui/pull/40

@JLHwung, please don’t feel bad about accidentally publishing the other plugin. It’s all good! 😄
